version: "3"

services:
  dbPostgres:
    image: postgres:10
    ports:
      - 5432:5432

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  web:
    build: ./
    ports:
      - 8000:8000

    links:
      - dbPostgres
